# Site settings
title: April Mintac Pineda
description: 'Guides, tutorials, and enlightenment.'
url: 'https://aprilmintacpineda.github.io'
baseurl: '/blog'
google_analytics: 'UA-111722788-2'
disqus_shortname: 'aprilmintacpineda'

author:
  name: 'April Mintac Pineda'
  twitter_username: aprmintacpineda
  facebook_username: aprilmintacpineda
  github_username:  aprilmintacpineda
  linkedin_username:  aprilmintacpineda

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
